[View in Colaboratory](https://colab.research.google.com/github/nurkayevaa/lambda/blob/master/Anel_Data_Preparation_Sprint_Challenge_Master.ipynb)

# Data Preparation

**Due Date:** April 21st @ 12:00 p.m. PST

Below are examples of the Titanic dataset, containing passenger records on board the titanic, and the OKCupid dataset, containing records authorized by OKCupid for use in Machine Learning research.

Your assignment is to combine the results of the Titanic and OKCupid datasets. You should replace each passenger aboard the titanic and their relevant data with a matching individual from the OKCupid dataset.

There should be no duplicates in the remaining dataset, with no NaNs, nulls, or missing information. More specifics at the bottom.

In [16]:
#The titanic dataset is part of the seaborn package
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

# The first few records
print(titanic.head(17))

    survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500       

In [3]:
# 891 passengers with 15 data entries per
print(titanic.shape)

(891, 15)


### OKCupid

The OKCupid dataset is 150MB and needs to be downloaded to your Colab session before you can load it. It loads using the same command as the titanic.

In [4]:
!wget https://www.dropbox.com/s/kurta6eazegc3su/JSE_OkCupid_profiles.csv?raw=1 -O /tmp/JSE_OkCupid_profiles.csv

--2018-04-21 15:38:24--  https://www.dropbox.com/s/kurta6eazegc3su/JSE_OkCupid_profiles.csv?raw=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.7.1, 2620:100:6016:1::a27d:101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.7.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.dropboxusercontent.com/content_link/tg6EFjyR44E5TeMvfqEy54agYPH3ospK2AUe8BZaJbFDNAGCo79HE5U5qRoFMskT/file [following]
--2018-04-21 15:38:24--  https://dl.dropboxusercontent.com/content_link/tg6EFjyR44E5TeMvfqEy54agYPH3ospK2AUe8BZaJbFDNAGCo79HE5U5qRoFMskT/file
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.7.6, 2620:100:601a:6::a27d:706
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.7.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151614805 (145M) [text/csv]
Saving to: ‘/tmp/JSE_OkCupid_profiles.csv’

/tmp/JSE_OkCupid_pr 100%[===================>] 144.59M  38.4MB/s    in 3.8

In [5]:
#Examining the OKCupid dataset
okcupid = pd.read_csv('/tmp/JSE_OkCupid_profiles.csv')

# almost 60000 individuals with 31 columns each
print(okcupid.shape)

# There are many more columns in OKCupid than titanic
print(okcupid.columns)


(59946, 31)
Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')


In [6]:
# The number of unique entries for each column
for column in okcupid.columns:
  print(column, okcupid[column].unique().size)

age 54
body_type 13
diet 19
drinks 7
drugs 4
education 33
essay0 54351
essay1 51517
essay2 48636
essay3 43534
essay4 49261
essay5 48964
essay6 43604
essay7 45555
essay8 39325
essay9 45444
ethnicity 218
height 61
income 13
job 22
last_online 30123
location 199
offspring 16
orientation 3
pets 16
religion 46
sex 2
sign 49
smokes 6
speaks 7648
status 5


In [0]:
print(okcupid[1:10].isnull())

     age  body_type   diet  drinks  drugs  education  essay0  essay1  essay2  \
1  False      False  False   False  False      False   False   False   False   
2  False      False  False   False   True      False   False   False   False   
3  False      False  False   False   True      False   False   False   False   
4  False      False   True   False  False      False   False   False   False   
5  False      False  False   False   True      False   False   False   False   
6  False      False  False   False  False      False   False   False   False   
7  False      False  False   False  False      False    True   False   False   
8  False       True  False   False   True      False    True   False    True   
9  False      False  False   False  False      False   False   False   False   

   essay3   ...    location  offspring  orientation   pets  religion    sex  \
1    True   ...       False      False        False  False     False  False   
2   False   ...       False       True   

### Duplicates

There are no duplicates in OKCupid and 107 titanic duplicates.

In [0]:
print(okcupid.duplicated().sum())
print(titanic.duplicated().sum())

0
107


## Instructions

Titanic contains 891 records with 107 duplicates. The final table should contain 784 records. The titanic dataset is also full of  redudant columns: `survived : alive`, `sex : who : adult_male`, which can be identified if they are truly redundant and can be removed if so.

The OKCupid dataset has ~60k records. There are 31 columns that match many of the features (importantly age/sex) in the titanic set.

Update each row of the titanic dataset to contain OKCupid data that matches in demographic information. Select a few columns from the OKCUpid dataset to transfer to the titanic dataset as well to increase the personality of each entry. Do not move the extremely long written records in the OKCupid dataset as part of this process. Those records will be useful later for NLP and text mining.

_Document and justify your decisions!_

In [0]:

#titanic.loc[titanic.duplicated(), :]
titanic.loc[titanic.duplicated(keep='first'), :]
titanicnd = titanic.drop_duplicates(keep='first')
#print(titanic.head(1))
#print('okcupid')
#print(okcupid.head(1))
okcupid['age'] = okcupid['age'].astype(float)

cleanup_nums = {"sex":     {"m": "male", "f": "female"}}
okcupid.replace(cleanup_nums, inplace=True)



result = pd.merge(titanicnd,
                 okcupid[['sex', 'age', 'pets', 'offspring']],
                 on='age', 
                 how='left')



In [13]:
result

survived  pclass   sex  age_x  sibsp  parch  fare embarked  class  \
0                0       3  male   22.0      1      0  7.25        S  Third   
1                0       3  male   22.0      1      0  7.25        S  Third   
2                0       3  male   22.0      1      0  7.25        S  Third   
3                0       3  male   22.0      1      0  7.25        S  Third   
4                0       3  male   22.0      1      0  7.25        S  Third   
5                0       3  male   22.0      1      0  7.25        S  Third   
6                0       3  male   22.0      1      0  7.25        S  Third   
7                0       3  male   22.0      1      0  7.25        S  Third   
8                0       3  male   22.0      1      0  7.25        S  Third   
9                0       3  male   22.0      1      0  7.25        S  Third   
10               0       3  male   22.0      1      0  7.25        S  Third   
11               0       3  male   22.0      1      0  7.25        S  Third   
12               0       3  male   22.0      1      0  7.25        S  Third   
13               0       3  male   22.0      1      0  7.25        S  Third   
14               0       3  male   22.0      1      0  7.25        S  Third   
15               0       3  male   22.0      1      0  7.25        S  Third   
16               0       3  male   22.0      1      0  7.25        S  Third   
17               0       3  male   22.0      1      0  7.25        S  Third   
18               0       3  male   22.0      1      0  7.25        S  Third   
19               0       3  male   22.0      1      0  7.25        S  Third   
20               0       3  male   22.0      1      0  7.25        S  Third   
21               0       3  male   22.0      1      0  7.25        S  Third   
22               0       3  male   22.0      1      0  7.25        S  Third   
23               0       3  male   22.0      1      0  7.25        S  Third   
24               0       3  male   22.0      1      0  7.25        S  Third   
25               0       3  male   22.0      1      0  7.25        S  Third   
26               0       3  male   22.0      1      0  7.25        S  Third   
27               0       3  male   22.0      1      0  7.25        S  Third   
28               0       3  male   22.0      1      0  7.25        S  Third   
29               0       3  male   22.0      1      0  7.25        S  Third   
...            ...     ...   ...    ...    ...    ...   ...      ...    ...   
20673617         0       3  male   32.0      0      0  7.75        Q  Third   
20673618         0       3  male   32.0      0      0  7.75        Q  Third   
20673619         0       3  male   32.0      0      0  7.75        Q  Third   
20673620         0       3  male   32.0      0      0  7.75        Q  Third   
20673621         0       3  male   32.0      0      0  7.75        Q  Third   
20673622         0       3  male   32.0      0      0  7.75        Q  Third   
20673623         0       3  male   32.0      0      0  7.75        Q  Third   
20673624         0       3  male   32.0      0      0  7.75        Q  Third   
20673625         0       3  male   32.0      0      0  7.75        Q  Third   
20673626         0       3  male   32.0      0      0  7.75        Q  Third   
20673627         0       3  male   32.0      0      0  7.75        Q  Third   
20673628         0       3  male   32.0      0      0  7.75        Q  Third   
20673629         0       3  male   32.0      0      0  7.75        Q  Third   
20673630         0       3  male   32.0      0      0  7.75        Q  Third   
20673631         0       3  male   32.0      0      0  7.75        Q  Third   
20673632         0       3  male   32.0      0      0  7.75        Q  Third   
20673633         0       3  male   32.0      0      0  7.75        Q  Third   
20673634         0       3  male   32.0      0      0  7.75        Q  Third   
20673635         0       3  male   32.0      0      0  7.75 

### Benchmark

The titanic dataset is very popular for beginning Data Science training.

Your final dataset should perfectly match these two obvious and famous benchmarks of the titanic data, with other new, interesting analysis available from your combinations:

In [22]:
titanicnd.groupby('sex')[['survived']].mean()
result.groupby('sex')[['survived']].mean()

survived
sex             
female  0.740614
male    0.219347

In [0]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

### Suggested search terms

python pandas replace columns

python pandas concatenate columns

python pandas concatenate rows

python pandas remove duplicates

python pandas merge and join records